"""empty message

Revision ID: 19b603522c7d
Revises: 680f360a815d
Create Date: 2018-03-27 09:40:46.668180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b603522c7d'
down_revision = '680f360a815d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('intro', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'intro')
    # ### end Alembic commands ###
