"""empty message

Revision ID: 1d2356fa49e5
Revises: 19b603522c7d
Create Date: 2018-03-27 09:45:16.601579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2356fa49e5'
down_revision = '19b603522c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'intro',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'intro',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
