"""empty message

Revision ID: 37cca9a97202
Revises: a807e9fc0739
Create Date: 2018-03-30 15:32:43.573109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37cca9a97202'
down_revision = 'a807e9fc0739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone', sa.String(length=15), nullable=True))
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_column('customers', 'phone')
    # ### end Alembic commands ###
