"""empty message

Revision ID: 680f360a815d
Revises: a4370c451013
Create Date: 2018-03-27 08:57:49.456007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680f360a815d'
down_revision = 'a4370c451013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'usp1',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'usp2',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'usp3',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'usp3',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'usp2',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'usp1',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
