"""empty message

Revision ID: a807e9fc0739
Revises: 1d2356fa49e5
Create Date: 2018-03-30 14:30:20.340139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a807e9fc0739'
down_revision = '1d2356fa49e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('customers', sa.Column('last_name', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_customers_first_name'), 'customers', ['first_name'], unique=False)
    op.create_index(op.f('ix_customers_last_name'), 'customers', ['last_name'], unique=False)
    op.drop_index('ix_customers_name', table_name='customers')
    op.drop_column('customers', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_index('ix_customers_name', 'customers', ['name'], unique=False)
    op.drop_index(op.f('ix_customers_last_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_first_name'), table_name='customers')
    op.drop_column('customers', 'last_name')
    op.drop_column('customers', 'first_name')
    # ### end Alembic commands ###
